    language: python

    sudo: required
    dist: trusty

    python:
      - 2.7
      - 3.5

    services:
      - postgresql

    addons:
      postgresql: "9.3"

    install:
      - gem install taskjuggler
      - pip install sqlalchemy psycopg2 jinja2 alembic Mako MarkupSafe python-editor nose coverage pytz

    before_script:
      - psql --version
      - pg_config --version
      - tj3 --version
      - sudo ln -s $(which tj3) /usr/local/bin/tj3
      - psql -c "CREATE DATABASE stalker_test;" -U postgres
      - psql -c "CREATE USER stalker_admin WITH PASSWORD 'stalker';" -U postgres

    script:
      - nosetests --verbosity=1 --cover-erase --with-coverage --cover-package=stalker
