    language: python

    sudo: required
    dist: trusty

    python:
      - 2.6
      - 2.7
      - 3.3
      - 3.4
      - 3.5

    services:
      - postgresql

    addons:
      postgresql: "9.5"

    install:
      - gem install taskjuggler
      - pip install sqlalchemy psycopg2 jinja2 alembic Mako MarkupSafe python-editor pytz tzlocal pytest pytest-xdist pytest-cov codeclimate-test-reporter

    before_script:
      - psql --version
      - pg_config --version
      - tj3 --version
      - sudo ln -s $(which tj3) /usr/local/bin/tj3
      - psql -c "CREATE USER stalker_admin WITH PASSWORD 'stalker' SUPERUSER INHERIT CREATEDB CREATEROLE NOREPLICATION;" -U postgres
      - psql -c "CREATE DATABASE stalker_test WITH OWNER = stalker_admin ENCODING = 'UTF8' TABLESPACE = pg_default CONNECTION LIMIT = -1;" -U postgres

    script:
      - py.test -n auto --cov-report= --cov=stalker tests

    after_success:
      - codeclimate-test-reporter
